### PR TITLE
Fix blue glow on input field

### PR DESCRIPTION
**Pull request by magic890**
Fixed blue glow on input field.

### CODE REVIEW

**Comment by badboy** [comment]
Why the `!important`?

**Comment by magic890** [comment]
To prevent other frameworks and default browser behaviours. If you want, in this case, you can omit it.

**Comment by badboy** [comment]
There's a reason that other frameworks and the browser might change it.

**Comment by badboy** [comment]
Merged by c4e96eab3294115842f5de3e8b737daebd1dc6dc

**Pull request closed without merging**
